config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  resources :posts, only: %i(new show create destroy) do
    resources :comments, only: %i(create destroy)
    resource :likes, only: %i(create destroy)
  end
  resources :users, except: %i(index new edit)
  get '/current_user/edit', to: 'users#edit'
  get '/signup', to: 'users#new'
  delete '/signout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  namespace :api do
    resources :posts, only: %i(index destroy) do
      resources :likes, only: %i(create destroy)
      resources :comments, only: %i(destroy)
    end
    resources :users, only: %i(show)
  end

  get 'tos', to: 'home#tos', as: 'tos'
  get 'privacy_policy', to: 'home#privacy_policy'
  match '*path' => 'application#error404', via: :all
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  with_options presence: true do
    validates :uid
    validates :provider
    validates :name, length: { maximum: 28 }
  end
  validates :uid, uniqueness: { scope: :provider }

  def self.find_from_omniauth(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    User.where(provider:, uid:).first
  end

  def self.new_from_omniauth(auth_hash)
    User.new(
      name: auth_hash[:info][:name],
      icon_url: auth_hash[:info][:image],
      provider: auth_hash[:provider],
      uid: auth_hash[:uid]
    )
  end

  def liked?(post)
    likes.exists?(post_id: post.id)
  end
end

app/controllers/api/users_controller.rb
# frozen_string_literal: true

class API::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_signin, only: %i[new edit update destroy]
  before_action :set_user, only: %i[show update destroy]

  def new; end

  def show; end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to @user, notice: 'アカウントを登録しました'
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報を編集しました'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to root_path, notice: 'アカウントを削除しました'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :url, :provider, :uid, :icon_url)
  end
end

app/views/users/edit.html.slim
article.article.container
  h2.title.is-3
    | アカウント編集
  = render 'shared/errors', object: @user
  = form_with(model: @user, local: true) do |form|
    .image.is-128x128
      = image_tag(@user.icon_url, alt: 'user_icon')
    .field
      .label
        = form.label :name, 'アカウント名'
    .field
      .control
        = form.text_field :name, class: 'input'
    .field
      .label
        = form.label :url, 'ホームページ(任意)'
    .field
      .control
        = form.text_field :url, class: 'input'
    .control
      .buttons
        = form.submit 'アカウント更新', class: 'button is-primary'
  .delete-account
    = link_to 'アカウント削除', @user, method: :delete, data: { confirm: 'アカウントを削除してもよろしいですか？' }

  = link_to 'マイページへ戻る', @user

app/views/users/new.html.slim
article.article.container
  h2.title.is-3 アカウント登録
  = render 'shared/errors', object: @user
  = form_with(model: @user, local: true) do |form|
    = form.hidden_field :provider
    = form.hidden_field :uid
    ul.select-icons
      li.select-icon
        = form.label :icon_url, value: @user.icon_url
          .image.is-96x96
            = image_tag(@user.icon_url)
        = form.radio_button :icon_url, @user.icon_url
      li.select-icon
        = form.label :icon_url, value: 'icon_user_f.png'
          .image.is-96x96
            = image_tag('icon_user_f.png')
        = form.radio_button :icon_url, 'icon_user_f.png'
      li.select-icon
        = form.label :icon_url, value: 'icon_user_m.png'
          .image.is-96x96
            = image_tag('icon_user_m.png')
        = form.radio_button :icon_url, 'icon_user_m.png'
    .field
      .label
        = form.label :name, 'アカウント名'
    .field
      .control
        = form.text_field :name, class: 'input'
    .field
      .label
        = form.label :url, 'ホームページ(任意)'
    .field
      .control
        = form.text_field :url, class: 'input'
    .control
      .buttons.is-right
        = form.submit 'アカウント登録', class: 'button is-primary'

  = link_to 'トップページへ戻る', root_path

app/views/users/show.html.slim
article.article.container
  .media.profile
    .media-left
      .image.is-128x128
        = image_tag @user.icon_url, alt: 'user_icon'
    .media-content
      .content
        h2.title.is-4
          = @user.name
        .sub-title
          = link_to @user.url, @user.url
      - if current_user == @user
        .buttons.profile-button
          = link_to 'アカウント編集', current_user_edit_path, class: 'button'
          = link_to 'ログアウト', signout_path, method: :delete, class: 'button'

  - if current_user
    #js-user-posts(data-user-id=params[:id] data-current-user-id=current_user.id)
  - else
    #js-user-posts(data-user-id=params[:id])

  = link_to 'トップページへ戻る', root_path