config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  resources :posts, only: %i(new show create destroy) do
    resources :comments, only: %i(create destroy)
    resource :likes, only: %i(create destroy)
  end
  resources :users, except: %i(index new edit)
  get '/current_user/edit', to: 'users#edit'
  get '/signup', to: 'users#new'
  delete '/signout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  namespace :api do
    resources :posts, only: %i(index destroy) do
      resources :likes, only: %i(create destroy)
      resources :comments, only: %i(destroy)
    end
    resources :users, only: %i(show)
  end

  get 'tos', to: 'home#tos', as: 'tos'
  get 'privacy_policy', to: 'home#privacy_policy'
  match '*path' => 'application#error404', via: :all
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def tos; end

  def privacy_policy; end
end

app/views/home/_description.slim
article.description
  h1.top-title
    = image_tag('nursepicks_top.png', alt: 'top_logo')
  h2.top-subtitle
    p
      | 看護師で作る、看護記事ブックマークサイト
  section.description-content.container
    - if cookies[:nursepicks_usage] == 'hide'
      .hide-usage-message
        a#js-hide-usage
          | このサイトの使い方
      .usage.is-hidden
        .hide-usage-button
          button.delete.is-large#js-hide-usage
        .columns
          .column
            .using
              h3.title.is-5.has-text-centered
                | 探す・読む
              .using-image.has-text-centered
                = image_tag('icon_read.png', size: '96x96', alt: 'read_icon')
              .subtitle.is-6
                p 投稿された価値ある看護記事や論文を、簡単に読むことができます。<br>記事に付けられたコメントも確認できます。
          .column
            .using
              h3.title.is-5.has-text-centered
                | 投稿する
              .using-image.has-text-centered
                = image_tag('icon_post.png', size: '96x96', alt: 'post_icon')
              .subtitle.is-6
                p 看護に役立つ記事・論文のURLを登録してください。<br>自分で書いた記事やYouTubeもURLがあれば投稿できます。<br>記事を投稿したりコメントするには、アカウント登録が必要です。
    - else
      .hide-usage-message.is-hidden
        a#js-hide-usage
          | このサイトの使い方
      .usage
        .hide-usage-button
          button.delete.is-large#js-hide-usage
        .columns
          .column
            .using
              h3.title.is-5.has-text-centered
                | 探す・読む
              .using-image.has-text-centered
                = image_tag('icon_read.png', size: '96x96', alt: 'read_icon')
              .subtitle.is-6
                p 投稿された価値ある看護記事や論文を、簡単に読むことができます。<br>記事に付けられたコメントも確認できます。
          .column
            .using
              h3.title.is-5.has-text-centered
                | 投稿する
              .using-image.has-text-centered
                = image_tag('icon_post.png', size: '96x96', alt: 'post_icon')
              .subtitle.is-6
                p 看護に役立つ記事・論文のURLを登録してください。<br>自分で書いた記事やYouTubeもURLがあれば投稿できます。<br>記事を投稿したりコメントするには、アカウント登録が必要です。
  section.description-button
    button.button.is-primary.is-large.post-button#js-modal data-modal='post-modal'
      | 記事を投稿する
    .modal#post-modal
      .modal-background#js-modal data-modal='post-modal'
      .modal-card
        .modal-card-head
          p.modal-card-title
            | 記事を投稿する
          button.delete#js-modal aria-label="close" data-modal='post-modal'
        .modal-card-body
          .post-description.notification.is-info.is-light
            .content
              ul
                li
                  | 看護記事のURLをこちらに入れて「記事の投稿」をクリック。
                li
                  | PDFファイルの論文も、URLがあれば投稿可能です。
                li
                  | メディカルオンラインの論文など、URLに自身のIDが入っているページも投稿できますが、他者に共有できない可能性があります。
          = form_with(model: @post, local: true) do |form|
            .content
              = render 'shared/errors', object: @post
              .field.has-text-left
                = form.label :url, class: 'label'
              .field-body.is-grouped
                .field.is-expanded
                  .control
                    = form.text_field :url, class: 'input', placeholder: 'https://www.example.com'
                .control
                  = form.submit '記事の投稿', class: 'button is-right is-primary'

app/views/home/_footer.html.slim
footer.footer
  .container
    nav.has-text-right
      ul.footer-items
        li.footer-item
          = link_to '利用規約', tos_path
        li.footer-item
          = link_to 'プライバシーポリシー', privacy_policy_path
      .footer-icons
        .twitter-icon
          = link_to 'https://twitter.com/nurse_picks', target: :_blank, rel: 'noopener'
            i.fa-brands.fa-square-twitter.fa-2x
        .github-icon
          = link_to 'https://github.com/garammasala29', target: :_blank, rel: 'noopener'
            i.fa-brands.fa-square-github.fa-2x
      p
        | &copy;NursePicks 2022

app/views/home/_header.html.slim
nav
  .navbar role="navigation" aria-label="main navigation"
    .container
      .navbar-brand
        .navbar-item
          - unless request.path == '/'
            h1.image.header-log
              = link_to image_tag('nursepicks_head.png', alt: 'header_logo'), root_path
      .navbar-menu
        .navbar-end
          - if signed_in?
            - unless request.path.match?(/user/)
              .navbar-item
                .icon-image
                  = link_to image_tag(current_user.icon_url, alt: 'nav_user_icon'), current_user
          - else
            .navbar-item
              .buttons
                - if request.path == '/'
                  button.button#js-modal data-modal='signup'
                    | ユーザー登録
                  .modal#signup
                    .modal-background#js-modal data-modal='signup'
                    .modal-card
                      .modal-card-head
                        p.modal-card-title
                          | ユーザー登録
                        button.delete#js-modal aria-label="close" data-modal='signup'
                      .modal-card-body
                        .signup-description.notification.is-info.is-light
                          .content
                            p
                              | GoogleやTwitterでアカウント登録をしても、自分の名前や画像は使用せずにサービスを利用できます<br>
                              | 匿名性は担保されますので、安心してお使いください
                        .buttons.sns-buttons.is-centered
                          a.button.google-button href='/auth/google_oauth2' data-method='post'
                            = image_tag('logo_google.png', alt: 'google_logo')
                            span
                              | Googleで新規登録
                          a.button.twitter-button href='/auth/twitter' data-method='post'
                            i.fa-brands.fa-twitter
                            span
                              | Twitterで新規登録

                button.button.is-info#js-modal data-modal='signin'
                  | ログイン
                .modal#signin
                  .modal-background#js-modal data-modal='signin'
                  .modal-card
                    .modal-card-head
                      p.modal-card-title
                        | ログイン
                      button.delete#js-modal aria-label="close" data-modal='signin'
                    .modal-card-body
                      .buttons.sns-buttons.is-centered
                        a.button.google-button href='/auth/google_oauth2' data-method='post'
                          = image_tag('logo_google.png', alt: 'google_logo')
                          span
                            | Googleでログイン
                        a.button.twitter-button href='/auth/twitter' data-method='post'
                          i.fa-brands.fa-twitter
                          span
                            | Twitterでログイン

app/views/home/privacy_policy.html.slim
article.article.container
  .content
    header
      h1
        | プライバシーポリシー
      p
        | NursePicks（以下，「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。

    h2
      | 第1条（個人情報）
    p
      | 本サービスでは登録およびご利用に際して以下の情報を取得し、それらを個人情報として取り扱います。
    ol
      li
        | Googleに関する情報
      li
        | Twitterに関する情報
      li
        | その他本サービスへのアクセス時に生成されるログ

    h2
      | 第2条（個人情報を収集・利用する目的）
    p
      | 本サービスが個人情報を収集・利用する目的は，以下のとおりです。
    ol
      li
        | 本サービスサービスの提供・運営のため
      li
        | ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）
      li
        | メンテナンス，重要なお知らせなど必要に応じたご連絡のため
      li
        | 利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため
      li
        | ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため
      li
        | 上記の利用目的に付随する目的

    h2
      | 第3条（利用目的の変更）
    ol
      li
        | 本サービスは，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。
      li
        | 利用目的の変更を行った場合には，変更後の目的について，本サービス所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。

    h2
      | 第4条（個人情報の第三者提供）
    ol
      li
        | 本サービスは，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。
        ol
          li
            | 人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき
          li
            | 公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき
          li
            | 国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき
          li
            | 予め次の事項を告知あるいは公表し，かつ本サービスが個人情報保護委員会に届出をしたとき
            ol
              li
                | 利用目的に第三者への提供を含むこと
              li
                | 第三者に提供されるデータの項目
              li
                | 第三者への提供の手段または方法
              li
                | 本人の求めに応じて個人情報の第三者への提供を停止すること
              li
                | 本人の求めを受け付ける方法
      li
        | 前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。
        ol
          li
            | 本サービスが利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合
          li
            | 合併その他の事由による事業の承継に伴って個人情報が提供される場合
          li
            | 個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合

    h2
      | 第5条（プライバシーポリシーの変更）
    ol
      li
        | 本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。
      li
        | 本サービスが別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。

    p
      | 2022年9月1日制定
    p.has-text-right
      | 以上

app/views/home/tos.html.slim
article.article.container
  .content
    header
      h1
        | 利用規約
      p
        | この利用規約（以下，「本規約」といいます。）は，このウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。

    h2
      | 第1条（適用）
    ol
      li
        | 本規約は，ユーザーと本サービスの利用に関わる一切の関係に適用されるものとします。
      li
        | 本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。
      li
        | 本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。
    h2
      | 第2条（利用登録）
    ol
      li
        | 本サービスにおいては、登録希望者が本規約に同意の上、本サービスの定める方法によって利用登録を申請し、本サービスがこの承認を登録希望者に通知することによって、利用登録が完了するものとします。
      li
        | 本サービスは，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。
        ol
          li
            | 利用登録の申請に際して虚偽の事項を届け出た場合
          li
            | 本規約に違反したことがある者からの申請である場合
          li
            | その他，本サービスが利用登録を相当でないと判断した場合

    h2
      | 第3条（ユーザーIDおよびパスワードの管理）
    ol
      li
        | 本サービスは、Googleアカウントおよびパスワードの取り扱い関して、Google社の利用規約に準ずるものとします。
      li
        | 本サービスは、Twitterアカウントおよびパスワードの取り扱い関して、Twitter社の利用規約に準ずるものとします。

    h2
      | 第4条（利用料金および支払方法）
    p
      | ユーザーは本サービスを無料で利用することができます。そのため、料金の支払いに関する取り決めは一切しません。

    h2
      | 第5条（禁止事項）
    p
      | ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。
    ol
      li
        | 法令または公序良俗に違反する行為
      li
        | 犯罪行為に関連する行為
      li
        | 本サービスの他のユーザー，または第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為
      li
        | 本サービスの運営を妨害するおそれのある行為
      li
        | 他のユーザーに関する個人情報等を収集または蓄積する行為
      li
        | 不正アクセスをし，またはこれを試みる行為
      li
        | 他のユーザーに成りすます行為
      li
        | 本サービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為
      li
        | 本サービスの他のユーザーまたは第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為
      li
        | 以下の表現を含み，または含むと本サービスが判断する内容を本サービス上に投稿し，または送信する行為
        ol
          li
            | 過度に暴力的な表現
          li
            | 露骨な性的表現
          li
            | 人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現
          li
            | 自殺，自傷行為，薬物乱用を誘引または助長する表現
          li
            | その他反社会的な内容を含み他人に不快感を与える表現
      li
        | 以下を目的とし，または目的とすると本サービスが判断する行為
        ol
          li
            | 営業，宣伝，広告，勧誘，その他営利を目的とする行為（本サービスの認めたものを除きます。）
          li
            | 性行為やわいせつな行為を目的とする行為
          li
            | 面識のない異性との出会いや交際を目的とする行為
          li
            | 他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為
          li
            | 本サービス，本サービスの他のユーザー，または第三者に不利益，損害または不快感を与えることを目的とする行為
          li
            | その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為
      li
        | 宗教活動または宗教団体への勧誘行為
      li
        | その他，本サービスが不適切と判断する行為

    h2
      | 第6条（本サービスの提供の停止等）
    ol
      li
        | 本サービスは，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
        ol
          li
            | 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合
          li
            | 地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合
          li
            | コンピュータまたは通信回線等が事故により停止した場合
          li
            | その他，本サービスの提供が困難と判断した場合
      li
        | 本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。

    h2
      | 第7条（著作権）
    ol
      li
        | ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報に関してのみ，本サービスを利用し，投稿ないしアップロードすることができるものとします。
      li
        | ユーザーが本サービスを利用して投稿ないしアップロードした文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，本サービスは，本サービスを利用して投稿ないしアップロードされた文章，画像，映像等について，本サービスの改良，品質の向上，または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。
      li
        | 前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて本サービスまたは本サービスにその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。

    h2
      | 第8条（利用制限および登録抹消）
    ol
      li
        | 本サービスは，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。
        ol
          li
            | 本規約のいずれかの条項に違反した場合
          li
            | 登録事項に虚偽の事実があることが判明した場合
          li
            | 決済手段として当該ユーザーが届け出たクレジットカードが利用停止となった場合
          li
            | 料金等の支払債務の不履行があった場合
          li
            | 本サービスからの連絡に対し，一定期間返答がない場合
          li
            | 本サービスについて，最終の利用から一定期間利用がない場合
          li
            | その他，本サービスが本サービスの利用を適当でないと判断した場合
      li
        | 前項各号のいずれかに該当した場合，ユーザーは，当然に本サービスに対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。
      li
        | 本サービスは，本条に基づき本サービスが行った行為によりユーザーに生じた損害について，一切の責任を負いません。

    h2
      | 第9条（退会）
    p
      | ユーザーは，本サービスの定める退会手続により，本サービスから退会できるものとします。

    h2
      | 第10条（保証の否認および免責事項）
    ol
      li
        | 本サービスは，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。
      li
        | 本サービスは，本サービスに起因してユーザーに生じたあらゆる損害について、一切の責任を負いません。ただし，本サービスとユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。
      li
        | 前項ただし書に定める場合であっても，本サービスは，本サービスの過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（本サービスまたはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，本サービスの過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。
      li
        | 本サービスは，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。

    h2
      | 第11条（サービス内容の変更等）
    p
      | 本サービスは，ユーザーへの事前の告知をもって、本サービスの内容を変更、追加または廃止することがあり、ユーザーはこれを承諾するものとします。

    h2
      | 第12条（利用規約の変更）
    p
      | 本サービスは、必要と判断した場合には、ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお、本規約の変更後、本サービスの利用を開始した場合には、当該ユーザーは変更後の規約に同意したものとみなします。

    h2
      | 第13条（個人情報の取扱い）
    p
      | 本サービスは，本サービスの利用によって取得する個人情報については，本サービス「プライバシーポリシー」に従い適切に取り扱うものとします。

    h2
      | 第14条（通知または連絡）
    p
      | ユーザーと本サービスとの間の通知または連絡は，本サービスの定める方法によって行うものとします。本サービスは,ユーザーから,本サービスが別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。

    h2
      | 第15条（権利義務の譲渡の禁止）
    p
      | ユーザーは，本サービスの書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。

    h2
      | 第16条（準拠法・裁判管轄）
    ol
      li
        | 本規約の解釈にあたっては，日本法を準拠法とします。
      li
        | 本サービスに関して紛争が生じた場合には，本サービスの本店所在地を管轄する裁判所を専属的合意管轄とします。

    p
      | 2022年9月1日制定
    p.has-text-right
      | 以上