config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  resources :posts, only: %i(new show create destroy) do
    resources :comments, only: %i(create destroy)
    resource :likes, only: %i(create destroy)
  end
  resources :users, except: %i(index new edit)
  get '/current_user/edit', to: 'users#edit'
  get '/signup', to: 'users#new'
  delete '/signout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  namespace :api do
    resources :posts, only: %i(index destroy) do
      resources :likes, only: %i(create destroy)
      resources :comments, only: %i(destroy)
    end
    resources :users, only: %i(show)
  end

  get 'tos', to: 'home#tos', as: 'tos'
  get 'privacy_policy', to: 'home#privacy_policy'
  match '*path' => 'application#error404', via: :all
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :url, presence: true, uniqueness: true
  validates :title, length: { maximum: 100 }, presence: true
  acts_as_taggable_on :tags

  after_create TweetNotifier.new

  def scrape
    page = MetaInspector.new(url)
    self.title = page.title
    self.image_url = page.meta['og:image'].presence || 'logo_picks.png'
    self.site_name = page.meta['og:site_name']
  end
end

app/controllers/api/posts_controller.rb
# frozen_string_literal: true

class API::PostsController < ApplicationController
  before_action :require_signin, only: %i[destroy]

  def index
    @posts = Post.includes(:comments, :likes, :tags, :tag_taggings)
  end

  def destroy
    current_user.posts.find(params[:id]).destroy!
    head :no_content
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show destroy]
  before_action :require_signin, only: %i[create destroy]

  def index
    @post = Post.new
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def create
    @post = current_user.posts.new(post_params)

    unless @post.title
      begin
        @post.scrape
        return render :new
      rescue StandardError
        @post.image_url = 'logo_picks.png'
        return render :new
      end
    end

    if @post.save
      redirect_to @post, notice: "「#{@post.title}」を登録しました"
    else
      render :new
    end
  end

  def destroy
    @post.destroy!
    redirect_to root_path, notice: "「#{@post.title}」を削除しました"
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:url, :title, :site_name, :image_url, :tag_list)
  end
end

app/views/posts/index.html.slim
= render 'home/description'
- if current_user
  #js-posts(data-current-user-id=current_user.id)
- else
  #js-posts

app/views/posts/new.html.slim
article.article.container
  h2.title.is-3 新規記事登録
  = render 'shared/errors', object: @post
  = form_with(model: @post, local: true) do |form|
    .field
      .label
        = form.label :image_url, 'このサイトの画像'
      .new-post-image
        = image_tag(@post.image_url, alt: 'post_image')
    = form.hidden_field :image_url
    = form.hidden_field :url
    .field
      .label
        = form.label :title, 'サイトURL'
      .control
        = @post.url
    .field
      .label
        = form.label :title, '記事のタイトル'
    .field
      .control
        = form.text_field :title, class: 'input'
    .field
      .label
        = form.label :site_name, 'サイト元(任意)'
    .field
      .control
        = form.text_field :site_name, class: 'input'
    .field
      .label
        = form.label :tag_list, 'タグ(循環器、小児、終末期、論文など)', for: 'js-post-tags'
    .field
      .control
        = text_field_tag 'post[tag_list]', @post.tag_list.join(','), type: 'text', id: 'js-post-tags'
    .control
      .buttons.is-right
        = form.submit '記事の登録', class: 'button is-primary'

  = link_to 'トップページへ戻る', root_path

app/views/posts/show.html.slim
article.article.container
  section
    .post.media
      .media-left.media-image
        = link_to @post.url, target: :_blank, rel: 'noopener noreferrer', class: 'post-image'
          = image_tag @post.image_url, alt: 'post_image', class: 'image is-64x64'
      .media-content
        h2.title.is-6
          = link_to @post.title, @post.url, target: :_blank, rel: 'noopener noreferrer'
        .sub-title
          = @post.site_name
          span.post-tags
            - @post.tag_list.each do |tag|
              span.post-tag
                = tag
      .media-right.has-text-centered
        - if current_user
          - if current_user.liked?(@post)
            = link_to post_likes_path(@post), method: :delete
              i.fa-solid.fa-heart.fa-2x.has-text-info
          - else
            = link_to post_likes_path(@post), method: :post
              i.fa-regular.fa-heart.fa-2x.has-text-info
        - else
          i.fa-solid.fa-heart.fa-2x.has-text-info
        p = @post.likes.count
        - if current_user == @post.user
          .delete-post-message
            = link_to '記事の削除', @post, method: :delete, data: { confirm: "「#{@post.title}」を削除してもよろしいですか？" }
    .post-list
      | 投稿 :
      .post-list-item
        = link_to image_tag(User.find(@post.user_id).icon_url, size: '28x28', alt: 'user_icon'), user_path(@post.user_id)
      .post-list-item
        = link_to User.find(@post.user_id).name, user_path(@post.user_id)
      .post-list-item
        = l @post.created_at, format: :short
  hr.post-separator
  section.comments
    - if @comments.presence
      - @comments.each do |comment|
        .comment.media
          .media-left
            = link_to image_tag(comment.user.icon_url, size: '32x32', alt: 'user_icon'), comment.user
            p = link_to comment.user.name, user_path(comment.user_id)
          .media-content
            = simple_format(comment.content)
          .media-right
            - if current_user == comment.user
              = link_to '削除', [@post, comment], method: :delete, data: { confirm: "「#{comment.content}」を削除してもよろしいですか？" }
    - else
      .empty-message
        i.fa-regular.fa-face-sad-tear
        .empty-message-text
          | 投稿されているコメントはまだありません。
        p
          | 記事の感想を投稿してみましょう！
  section.comment-area
    = render 'shared/errors', object: @comment
    - if signed_in?
      = form_with(model: [@post, @comment], local: true) do |form|
        .field.is-horizontal
          .field-label.is-normal
            .label
              = form.label :content, 'コメント'
          .field-body
            .field
              .control
                = form.text_area :content, class: 'textarea'
        .field.is-horizontal
          .field-body
            .field.is-grouped.is-grouped-right
              .control
                = form.submit 'コメントの投稿', class: 'button'
    - else
      hr.post-separator
      p.notification.is-info.is-light
        | ログインするとコメントできます

  = link_to 'トップページへ戻る', root_path